### PR TITLE
Dev reactjs project generator

### PR DESCRIPTION
**Pull request by hurelhuyag**
Please review https://github.com/vlingo/xoom-turbo/pull/25 before reviewing this.

Update: 
Dependant on https://github.com/vlingo/xoom-turbo/pull/26

### CODE REVIEW

**Comment by hurelhuyag** [comment]
Hello, @danilo-ambrosio ReactJS project generator generates npm project only. It means currently not configured with backend HTTP handlers. Only can run independently with `npm install; npm run start`. I need more time to integrate with backend HTTP handlers.

**Comment by hurelhuyag** [comment]
UiResoure implemented. But currently, I have no idea how to implement when annotation and auto dispatch enabled.

**Comment by VaughnVernon** [comment]
@danilo-ambrosio Please assist @hurelhuyag with this. As far as I understand there should be only one resource handler for ReactJS. It could be useful to support either or:

- No UI scaffolding selected:
  - generate resource handlers as done currently
- UI scaffolding selected:
  - ReactJS: generate single resource handler
  - Svelte: ???
  - VueJS: generate single resource handler
  - AngularJS: ???

**Comment by hurelhuyag** [comment]
This PR should work after vlingo/xoom-turbo#26 merged.

**Comment by hurelhuyag** [comment]
Failing tests fixed. @danilo-ambrosio please review now.

**Review by danilo-ambrosio — APPROVED** [review]

**Pull request merged**
